spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 'facebook id'
            clientSecret: 'facebook secret'

          google:
            client-id: 'google id'
            client-secret: 'google secret'
